// <auto-generated />
using System;
using DataEmployees;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataEmployees.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231114185744_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("DataEmployees.Entities.EmployeesEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("employee_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Fire")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Hire")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("Stanowisko")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("employees");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Created = new DateTime(2012, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Dział IT",
                            Fire = new DateTime(2015, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hire = new DateTime(2012, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Adam",
                            Pesel = "11111111111",
                            Stanowisko = "CyberSecEngineer",
                            Surname = "Kowalski"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
